### ISSUE TITLE
Corrigir logo

### ISSUE THREAD

**Issue by breakzplatform** [DevFestNordeste/landing#3]
Outspace tem que ser corrigido (o designer já enviou a modificação)

**Comment by vitormalencar** [comment]
onde ta ?

**Comment by breakzplatform** [comment]
essa tarefa e minha. foca nas outras

**Comment by juarezpaf** [comment]
@joselitojunior removi o seu número do seu comentário só para não criarem caso ;)

**Comment by breakzplatform** [comment]
@juarezpaf <3
